from __future__  import absolute_import

from django.conf import settings
from kombu import Queue

# BROKER SETTINGS
BROKER_URL = settings.BROKER_URL
BROKER_HEARTBEAT = settings.BROKER_HEARTBEAT
BROKER_POOL_LIMIT = settings.BROKER_POOL_LIMIT
BROKER_CONNECTION_TIMEOUT = settings.BROKER_CONNECTION_TIMEOUT

# CELERY EVENTS SETTINGS
CELERY_SEND_EVENTS = settings.CELERY_SEND_EVENTS
CELERY_EVENT_QUEUE_EXPIRE = settings.CELERY_EVENT_QUEUE_EXPIRE

# RESULT SETTINGS
CELERY_RESULT_BACKEND = settings.CELERY_RESULT_BACKEND
CELERY_TASK_RESULT_EXPIRES = 3600  # 1 hour

# SERIALIZATION SETTINGS
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_REDIS_MAX_CONNECTIONS = 6

# GENERAL SETTINGS
CELERYD_MAX_TASKS_PER_CHILD = 3
CELERY_TIMEZONE = settings.TIME_ZONE
CELERY_DEFAULT_QUEUE = 'blah'
CELERY_DEFAULT_EXCHANGE = 'blah'
CELERY_DEFAULT_ROUTING_KEY = 'blah'
CELERY_QUEUES = (
    Queue('blah', routing_key='blah'),
)

# EVENT SETTINGS
CELERY_SEND_EVENTS = True
CELERY_SEND_TASK_SENT_EVENT = True

#CELERYBEAT SETTINGS
CELERYBEAT_SCHEDULE = {
}